apiVersion: v1
kind: Service
metadata:
  name: crud-microservice
  labels:
    app: crud-microservice
spec:
  type: NodePort
  selector:
    app: crud-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
      nodePort: 30007
