apiVersion: v1
kind: Service
metadata:
  name: crud-microservice
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      nodePort: 30000
  selector:
    app: crud-microservice
  type: NodePort